"""Generates and manages the recommended power-on/self-heal automations
for one device, as a plain YAML file dropped into the user's automations/
folder.

This is genuinely different in kind from everything else in this
component: it reaches outside the integration's own domain and writes
into a folder it doesn't own, rather than working through HA's own APIs
(entities, services, config entries). Deliberately opt-in for that
reason - see config_flow.py's async_step_setup_automations - and cleaned
up automatically on entry removal (async_remove_entry in __init__.py),
so uninstalling the integration doesn't leave orphaned automations behind.

Only works for setups using `automation: !include_dir_merge_list
automations/` - the same pattern this project's own YAML automations
have always assumed. HA's own built-in automation editor is itself
hardcoded to a single fixed file (automations.yaml, confirmed against
homeassistant/config.py's AUTOMATION_CONFIG_PATH) - there is no portable,
universal way to programmatically add an automation that adapts to every
possible way a user might have their config structured. This targets the
one pattern already established as this project's actual setup.

The self-heal automation is deliberately leaner than the original
hand-written YAML version: webhook re-registration is now handled
entirely by RecoveryManager in Python (see recovery.py) as part of its
recovery event, so the automation's only remaining job is the one thing
that genuinely can't move into Python - resurrecting the process via
androidtv.adb_command.
"""

from __future__ import annotations

import logging
import os

from homeassistant.core import HomeAssistant
from homeassistant.helpers import device_registry as dr

from .const import DOMAIN

_LOGGER = logging.getLogger(__name__)

START_SERVICE_COMMAND = "am start-foreground-service -n dev.local.ttsbridge/.AnnouncementService"


def _automation_filename(entry_id: str) -> str:
    return f"ttsbridge_{entry_id}.yaml"


def _render_automations_yaml(entry_id: str, host: str, media_player_entity_id: str, device_id: str | None) -> str:
    recovered_announce = ""
    if device_id:
        # device_id, not entity_id: the notify entity's *name* can change
        # (the user renaming it is a completely normal thing to do), but
        # the device_id never does - HA resolves device_id -> whatever
        # entity currently exists for it at call time, not at the moment
        # this file was generated. A hardcoded entity_id here previously
        # broke silently the first time the entity got renamed.
        recovered_announce = f"""
    - action: notify.send_message
      target:
        device_id: {device_id}
      data:
        message: "Announcement bridge recovered\""""

    return f"""\
# Auto-generated by the TTS Bridge integration for entry {entry_id} ({host}).
# Safe to edit, but changes will be OVERWRITTEN if the device is ever
# removed and re-added through the integration. Delete this file (and
# reload automations) to remove it manually.

- id: ttsbridge_{entry_id}_start_on_power_on
  alias: "TTS Bridge ({host}) - start on power on"
  trigger:
    - trigger: state
      entity_id: {media_player_entity_id}
      to: "on"
  action:
    - delay: "00:00:05"
    - action: androidtv.adb_command
      target:
        entity_id: {media_player_entity_id}
      data:
        command: "{START_SERVICE_COMMAND}"

- id: ttsbridge_{entry_id}_self_heal
  alias: "TTS Bridge ({host}) - self heal"
  trigger:
    - trigger: event
      event_type: ttsbridge_recovery_needed
  condition:
    - condition: template
      value_template: "{{{{ trigger.event.data.entry_id == '{entry_id}' }}}}"
  action:
    - action: androidtv.adb_command
      target:
        entity_id: {media_player_entity_id}
      data:
        command: "{START_SERVICE_COMMAND}"{recovered_announce}
"""


async def async_install_automations(
    hass: HomeAssistant, entry_id: str, host: str, media_player_entity_id: str
) -> None:
    """Write the automations file for one device and reload automations to pick it up."""
    registry = dr.async_get(hass)
    device = registry.async_get_device(identifiers={(DOMAIN, entry_id)})
    device_id = device.id if device else None
    if device_id is None:
        _LOGGER.warning(
            "Could not find the device registry entry for %s - the generated "
            "automation's 'recovered' announcement step will be omitted",
            entry_id,
        )

    content = _render_automations_yaml(entry_id, host, media_player_entity_id, device_id)
    path = hass.config.path("automations", _automation_filename(entry_id))

    def _write() -> None:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

    await hass.async_add_executor_job(_write)
    _LOGGER.info("Wrote automations for entry %s to %s", entry_id, path)
    await hass.services.async_call("automation", "reload", blocking=True)


async def async_remove_automations(hass: HomeAssistant, entry_id: str) -> None:
    """Delete the automations file for one device, if it exists, and reload."""
    path = hass.config.path("automations", _automation_filename(entry_id))

    def _remove() -> bool:
        if os.path.exists(path):
            os.remove(path)
            return True
        return False

    removed = await hass.async_add_executor_job(_remove)
    if removed:
        _LOGGER.info("Removed automations for entry %s (%s)", entry_id, path)
        await hass.services.async_call("automation", "reload", blocking=True)
